Update patch set 7
Patch Set 7:

> Patch Set 7: -Code-Review
> 
> > Patch Set 7:
> > 
> > > Patch Set 7:
> > > 
> > > > Patch Set 7:
> > > > 
> > > > (1 comment)
> > > > 
> > > > However, when I applied this commit, I got to be able to build it.
> > > 
> > > The right import should be "import android.support.customtabs.browseractions.R" instead of "import android.support.customtabs.R"? Looks like "import android.support.customtabs.R" would fail on ninja build.
> > 
> > 
> > I tried to replace "import android.support.customtabs.R" to "import android.support.customtabs.browseractions.R" and build using Gradle.
> > But it faild.
> 
> Do you have a build log with an error message?

<Build log (Japanese is mixed)>
Executing tasks: [:custom-tabs-client:customtabs:assembleDebug]

Configuration on demand is an incubating feature.
Configuration 'compile' in project ':custom-tabs-client:customtabs' is deprecated. Use 'implementation' instead.
Configuration 'androidTestCompile' in project ':custom-tabs-client:customtabs' is deprecated. Use 'androidTestImplementation' instead.
:custom-tabs-client:customtabs:preBuild UP-TO-DATE
:custom-tabs-client:customtabs:preDebugBuild UP-TO-DATE
:custom-tabs-client:customtabs:compileDebugAidl UP-TO-DATE
:custom-tabs-client:customtabs:compileDebugNdk NO-SOURCE
:custom-tabs-client:customtabs:compileDebugRenderscript UP-TO-DATE
:custom-tabs-client:customtabs:checkDebugManifest UP-TO-DATE
:custom-tabs-client:customtabs:generateDebugBuildConfig UP-TO-DATE
:custom-tabs-client:customtabs:prepareLintJar UP-TO-DATE
:custom-tabs-client:customtabs:generateDebugResValues UP-TO-DATE
:custom-tabs-client:customtabs:generateDebugResources UP-TO-DATE
:custom-tabs-client:customtabs:packageDebugResources UP-TO-DATE
:custom-tabs-client:customtabs:platformAttrExtractor UP-TO-DATE
:custom-tabs-client:customtabs:processDebugManifest UP-TO-DATE
:custom-tabs-client:customtabs:processDebugResources UP-TO-DATE
:custom-tabs-client:customtabs:generateDebugSources UP-TO-DATE
:custom-tabs-client:customtabs:javaPreCompileDebug UP-TO-DATE
:custom-tabs-client:customtabs:compileDebugJavaWithJavac
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuView.java:23: エラー: シンボルを見つけられません
import android.support.customtabs.browseractions.R;
                                                ^
  シンボル:   クラス R
  場所: パッケージ android.support.customtabs.browseractions
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuUi.java:28: エラー: シンボルを見つけられません
import android.support.customtabs.browseractions.R;
                                                ^
  シンボル:   クラス R
  場所: パッケージ android.support.customtabs.browseractions
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuAdapter.java:23: エラー: シンボルを見つけられません
import android.support.customtabs.browseractions.R;
                                                ^
  シンボル:   クラス R
  場所: パッケージ android.support.customtabs.browseractions
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuView.java:39: エラー: パッケージRは存在しません
                R.dimen.browser_actions_context_menu_min_padding);
                 ^
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuView.java:41: エラー: パッケージRは存在しません
                R.dimen.browser_actions_context_menu_max_width);
                 ^
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuUi.java:85: エラー: パッケージRは存在しません
                R.layout.browser_actions_context_menu_page, null);
                 ^
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuUi.java:101: エラー: パッケージRは存在しません
                (BrowserActionsFallbackMenuView) view.findViewById(R.id.browser_actions_menu_view);
                                                                    ^
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuUi.java:103: エラー: パッケージRは存在しません
        final TextView urlTextView = (TextView) view.findViewById(R.id.browser_actions_header_text);
                                                                   ^
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuUi.java:118: エラー: パッケージRは存在しません
        ListView menuListView = (ListView) view.findViewById(R.id.browser_actions_menu_items);
                                                              ^
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuAdapter.java:68: エラー: パッケージRは存在しません
                    R.layout.browser_actions_context_menu_row, null);
                     ^
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuAdapter.java:71: エラー: パッケージRは存在しません
                    (ImageView) convertView.findViewById(R.id.browser_actions_menu_item_icon);
                                                          ^
/home/elegant-belltree/Documents/git-push-hackathon/massongit/custom-tabs-client/customtabs/src/android/support/customtabs/browseractions/BrowserActionsFallbackMenuAdapter.java:73: エラー: パッケージRは存在しません
                    (TextView) convertView.findViewById(R.id.browser_actions_menu_item_text);
                                                         ^
エラー12個

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':custom-tabs-client:customtabs:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

12 actionable tasks: 1 executed, 11 up-to-date

Patch-set: 7
Reviewer: Masaya Suzuki <1267317@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>